const A = '/assets/';

export const blogPosts = [
  {
    id: 1,
    title: 'How to Plan a Timeless Destination Wedding in India',
    slug: 'plan-timeless-destination-wedding',
    category: 'Wedding Inspiration',
    image: `${A}adithya_infocus_6.webp`,
    date: 'MAY 30, 2024',
    readTime: '6 min read',
    author: 'PUSHPA KRISHNA KADALI',
    excerpt: 'A complete guide to planning your dream wedding with elegance, heritage palaces, and ease.',
    featured: true,
  },
  {
    id: 2,
    title: 'Candid vs Traditional Photography – What\'s Right for You?',
    slug: 'candid-vs-traditional-photography',
    category: 'Photography Tips',
    image: `${A}wedding-2.png`,
    date: 'MAY 15, 2024',
    readTime: '5 min read',
    author: 'Infocus Editorial',
    excerpt: 'Understand the styles and choose what fits your wedding story best.',
    featured: false,
  },
  {
    id: 3,
    title: 'Behind the Frame: How We Capture Raw Emotions',
    slug: 'behind-the-frame-raw-emotions',
    category: 'Behind The Scenes',
    image: `${A}239A5203_bts.webp`,
    date: 'MAY 10, 2024',
    readTime: '5 min read',
    author: 'PUSHPA KRISHNA KADALI',
    excerpt: 'A sneak peek into our process and the emotional unscripted moments behind the scenes.',
    featured: false,
  },
  {
    id: 4,
    title: 'Why Wedding Films Are the Memories That Last Forever',
    slug: 'wedding-films-memories-last-forever',
    category: 'Wedding Films',
    image: `${A}infocus_engagement_photography.webp`,
    date: 'MAY 05, 2024',
    readTime: '6 min read',
    author: 'PUSHPA KRISHNA KADALI',
    excerpt: 'Relive your wedding day through cinematic motion, sound, and heartfelt emotion.',
    featured: false,
  },
  {
    id: 5,
    title: '5 Things to Consider Before Booking Your Photographer',
    slug: '5-things-consider-booking-photographer',
    category: 'Wedding Planning',
    image: `${A}bridal-details-collage.png`,
    date: 'APRIL 28, 2024',
    readTime: '5 min read',
    author: 'Infocus Editorial',
    excerpt: 'Essential tips to help you choose the ideal photography team for your celebration.',
    featured: false,
  },
  {
    id: 6,
    title: 'A Royal Udaipur Wedding Full of Love & Magic',
    slug: 'royal-udaipur-wedding',
    category: 'Real Weddings',
    image: `${A}VSR03877_real_wedding.webp`,
    date: 'APRIL 20, 2024',
    readTime: '7 min read',
    author: 'Infocus Editorial',
    excerpt: 'Reliving the beautiful union set against the historic city of lakes and palaces.',
    featured: false,
  },
  {
    id: 7,
    title: 'Our Favorite Gear for Capturing Timeless Weddings',
    slug: 'favorite-gear-capturing-weddings',
    category: 'Equipment & Gear',
    image: `${A}DVI01775_gear.webp`,
    date: 'APRIL 15, 2024',
    readTime: '6 min read',
    author: 'PUSHPA KRISHNA KADALI',
    excerpt: 'The professional camera bodies, prime lenses, and drones we trust on every shoot.',
    featured: false,
  },
  {
    id: 8,
    title: 'The Art of the Pre-Wedding Shoot: Tips for Couples',
    slug: 'art-pre-wedding-shoot',
    category: 'Photography Tips',
    image: `${A}pre-wedding-beach.png`,
    date: 'APRIL 02, 2024',
    readTime: '5 min read',
    author: 'Infocus Editorial',
    excerpt: 'How to prepare for a relaxed, authentic pre-wedding photography session.',
    featured: false,
  },
  {
    id: 9,
    title: 'An Intimate Celebration in Bali – A Story of Love',
    slug: 'intimate-celebration-bali',
    category: 'Real Weddings',
    image: `${A}VSR03510_featured.webp`,
    date: 'APRIL 10, 2024',
    readTime: '6 min read',
    author: 'Infocus Editorial',
    excerpt: 'A stunning Bali wedding filled with raw emotions, scenic ocean views, and timeless moments.',
    featured: false,
  },
  {
    id: 10,
    title: 'Selecting the Perfect Bridal Jewellery for Your Big Day',
    slug: 'selecting-perfect-bridal-jewellery',
    category: 'Wedding Inspiration',
    image: `${A}heritage-couple-portrait.png`,
    date: 'MARCH 22, 2024',
    readTime: '5 min read',
    author: 'Infocus Editorial',
    excerpt: 'Expert advice on matching traditional South Indian gold and temple jewelry with bridal attire.',
    featured: false,
  },
  {
    id: 11,
    title: 'Top 10 South Indian Temple Wedding Venues',
    slug: 'top-10-temple-venues',
    category: 'Wedding Planning',
    image: `${A}temple-ceremony-couple.webp`,
    date: 'MARCH 15, 2024',
    readTime: '7 min read',
    author: 'Infocus Editorial',
    excerpt: 'Discover breathtaking traditional temple venues and heritage halls across AP & Telangana.',
    featured: false,
  },
  {
    id: 12,
    title: 'Crafting the Perfect Wedding Album Layout',
    slug: 'crafting-perfect-album-layout',
    category: 'Photography Tips',
    image: `${A}reception-2.png`,
    date: 'MARCH 05, 2024',
    readTime: '5 min read',
    author: 'PUSHPA KRISHNA KADALI',
    excerpt: 'How we sequence your photos into hand-bound flush mount albums that tell a story.',
    featured: false,
  },
  {
    id: 13,
    title: 'Top Luxury Wedding Venues in Hyderabad for 2026',
    slug: 'top-wedding-venues-hyderabad',
    category: 'Wedding Planning',
    image: `${A}VSR02742_contact.webp`,
    date: 'FEB 28, 2024',
    readTime: '7 min read',
    author: 'PUSHPA KRISHNA KADALI',
    excerpt: 'A curated guide to Taj Falaknuma Palace, ITC Kohenur, Boulder Hills, and grand convention centers in Hyderabad.',
    featured: false,
  },
  {
    id: 14,
    title: 'Best Telugu Wedding Photography Poses for Couples',
    slug: 'best-telugu-wedding-poses',
    category: 'Photography Tips',
    image: `${A}adithya_infocus_1.webp`,
    date: 'FEB 20, 2024',
    readTime: '5 min read',
    author: 'Infocus Editorial',
    excerpt: 'Classic and contemporary posing ideas for Telugu brides and grooms to look regal, confident, and natural.',
    featured: false,
  },
  {
    id: 15,
    title: 'Top Wedding Venues in Vijayawada & Andhra Pradesh',
    slug: 'top-wedding-venues-vijayawada',
    category: 'Wedding Planning',
    image: `${A}VSR03586_contact.webp`,
    date: 'FEB 14, 2024',
    readTime: '6 min read',
    author: 'PUSHPA KRISHNA KADALI',
    excerpt: 'Exploring luxury convention halls, riverside venues, and 5-star properties in Vijayawada for grand celebrations.',
    featured: false,
  },
  {
    id: 16,
    title: 'Traditional Telugu Wedding Rituals & Ceremonies Explained',
    slug: 'traditional-telugu-wedding-rituals-explained',
    category: 'Real Weddings',
    image: `${A}srinivasa-kalyanam-1.webp`,
    date: 'FEB 05, 2024',
    readTime: '8 min read',
    author: 'Infocus Editorial',
    excerpt: 'From Pelli Kuthuru, Mangala Snanam, Jeelakarra Bellam to Talambralu – celebrating ancient wedding traditions.',
    featured: false,
  },
  {
    id: 17,
    title: 'Cinematic Wedding Films vs Traditional Videos',
    slug: 'cinematic-films-vs-traditional-videos',
    category: 'Wedding Films',
    image: `${A}VSU00343_contact.webp`,
    date: 'JAN 28, 2024',
    readTime: '6 min read',
    author: 'PUSHPA KRISHNA KADALI',
    excerpt: 'Why modern couples choose high-production story-driven cinema over multi-hour raw traditional recordings.',
    featured: false,
  },
  {
    id: 18,
    title: 'Tips for Looking Natural and Relaxed in Wedding Photos',
    slug: 'tips-looking-natural-wedding-photos',
    category: 'Photography Tips',
    image: `${A}infocus_engagement_photography.webp`,
    date: 'JAN 18, 2024',
    readTime: '5 min read',
    author: 'Infocus Editorial',
    excerpt: 'Overcome camera shyness and capture warm, genuine expressions with these effortless photography tips.',
    featured: false,
  },
  {
    id: 19,
    title: 'Wedding Photography Trends Shaping 2026 Celebrations',
    slug: 'wedding-photography-trends-2026',
    category: 'Wedding Inspiration',
    image: `${A}yjhsqa.webp`,
    date: 'JAN 10, 2024',
    readTime: '7 min read',
    author: 'PUSHPA KRISHNA KADALI',
    excerpt: 'Editorial bridal portraits, FPV drone coverage, film grain aesthetics, and Instagram Reels storytelling.',
    featured: false,
  },
  {
    id: 20,
    title: 'Essential Wedding Photography Checklist for Couples',
    slug: 'essential-wedding-photography-checklist',
    category: 'Wedding Planning',
    image: `${A}bridal-details-collage.png`,
    date: 'JAN 02, 2024',
    readTime: '6 min read',
    author: 'Infocus Editorial',
    excerpt: 'Never miss a family portrait, detail shot, or emotional moment with our master wedding day checklist.',
    featured: false,
  }
];

export const blogCategories = [
  { name: 'Wedding Inspiration', count: 24 },
  { name: 'Photography Tips', count: 22 },
  { name: 'Wedding Films', count: 18 },
  { name: 'Behind The Scenes', count: 12 },
  { name: 'Real Weddings', count: 25 },
  { name: 'Wedding Planning', count: 20 },
  { name: 'Equipment & Gear', count: 10 },
];
