const A = '/assets/';

export const blogPosts = [
  {
    id: 1,
    title: 'How to Plan a Timeless Destination Wedding in India',
    slug: 'plan-timeless-destination-wedding',
    category: 'Wedding Inspiration',
    image: `${A}adithya_infocus_6.webp`,
    date: 'MAY 30, 2024',
    excerpt: 'A complete guide to planning your dream wedding with elegance and ease.',
    featured: true,
  },
  {
    id: 2,
    title: 'Candid vs Traditional Photography – What\'s Right for You?',
    slug: 'candid-vs-traditional-photography',
    category: 'Photography Tips',
    image: `${A}wedding-2.png`,
    date: 'MAY 15, 2024',
    excerpt: 'Understand the styles and choose what fits your story best.',
    featured: false,
  },
  {
    id: 3,
    title: 'Behind the Frame: How We Capture Raw Emotions',
    slug: 'behind-the-frame-raw-emotions',
    category: 'Behind The Scenes',
    image: `${A}239A5203_bts.webp`,
    date: 'MAY 10, 2024',
    excerpt: 'A sneak peek into our process and the moments you don\'t see.',
    featured: false,
  },
  {
    id: 4,
    title: 'Why Wedding Films Are the Memories That Last Forever',
    slug: 'wedding-films-memories-last-forever',
    category: 'Wedding Films',
    image: `${A}infocus_engagement_photography.webp`,
    date: 'MAY 05, 2024',
    excerpt: 'Relive your wedding day through motion, sound and emotion.',
    featured: false,
  },
  {
    id: 5,
    title: '5 Things to Consider Before Booking Your Photographer',
    slug: '5-things-consider-booking-photographer',
    category: 'Wedding Planning',
    image: `${A}bridal-details-collage.png`,
    date: 'APRIL 28, 2024',
    excerpt: 'Essential tips to help you make the perfect choice.',
    featured: false,
  },
  {
    id: 6,
    title: 'A Royal Udaipur Wedding Full of Love & Magic',
    slug: 'royal-udaipur-wedding',
    category: 'Real Weddings',
    image: `${A}VSR03877_real_wedding.webp`,
    date: 'APRIL 20, 2024',
    excerpt: 'Reliving the beautiful union set against the city of lakes.',
    featured: false,
  },
  {
    id: 7,
    title: 'Our Favorite Gear for Capturing Timeless Weddings',
    slug: 'favorite-gear-capturing-weddings',
    category: 'Equipment & Gear',
    image: `${A}DVI01775_gear.webp`,
    date: 'APRIL 15, 2024',
    excerpt: 'The tools we trust to create cinematic masterpieces.',
    featured: false,
  },
  {
    id: 8,
    title: 'The Art of the Pre-Wedding Shoot: Tips for Couples',
    slug: 'art-pre-wedding-shoot',
    category: 'Photography Tips',
    image: `${A}pre-wedding-beach.png`,
    date: 'APRIL 02, 2024',
    excerpt: 'How to prepare for a relaxed, authentic pre-wedding session.',
    featured: false,
  },
  {
    id: 9,
    title: 'An Intimate Celebration in Bali – A Story of Love',
    slug: 'intimate-celebration-bali',
    category: 'Real Weddings',
    image: `${A}VSR03510_featured.webp`,
    date: 'APRIL 10, 2024',
    excerpt: 'A stunning Bali wedding that was all about raw emotions, scenic beauty and timeless moments.',
    featured: false,
  },
  {
    id: 10,
    title: 'Selecting the Perfect Bridal Jewellery for Your Big Day',
    slug: 'selecting-perfect-bridal-jewellery',
    category: 'Wedding Inspiration',
    image: `${A}heritage-couple-portrait.png`,
    date: 'MARCH 22, 2024',
    excerpt: 'Expert advice on matching your jewelry to your wedding aesthetic.',
    featured: false,
  },
  {
    id: 11,
    title: 'Top 10 South Indian Temple Wedding Venues',
    slug: 'top-10-temple-venues',
    category: 'Wedding Planning',
    image: `${A}temple-ceremony-couple.webp`,
    date: 'MARCH 15, 2024',
    excerpt: 'Discover breathtaking traditional venues for a sacred ceremony.',
    featured: false,
  },
  {
    id: 12,
    title: 'Crafting the Perfect Wedding Album Layout',
    slug: 'crafting-perfect-album-layout',
    category: 'Photography Tips',
    image: `${A}reception-2.png`,
    date: 'MARCH 05, 2024',
    excerpt: 'How we sequence your photos to tell a beautiful, cohesive story.',
    featured: false,
  }
];

export const blogCategories = [
  { name: 'Wedding Inspiration', count: 18 },
  { name: 'Photography Tips', count: 14 },
  { name: 'Wedding Films', count: 12 },
  { name: 'Behind The Scenes', count: 10 },
  { name: 'Real Weddings', count: 16 },
  { name: 'Wedding Planning', count: 11 },
  { name: 'Equipment & Gear', count: 8 },
];
